In [1]:
import numpy as np

def create_board():
    board = np.zeros((3,3), dtype=int)
    return board


In [12]:
def place(board, player, position):
    if board[position] == 0:
        board[position] = player
        return board

board = create_board()
place(board, 1, (0, 0))


array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [4]:
def possibilities(board):
    return list(zip(*np.where(board == 0)))

possibilities(board)

[(0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

In [13]:
import random
def random_place(board, player):
    selections = possibilities(board)
    if len(selections) > 0:
        selection = random.choice(selections)
        place(board, player, selection)
    return board

random_place(board, 2)


array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 2]])

In [14]:
random.seed(1)
board = create_board()

for i in range(3):
    for player in [1, 2]:
        random_place(board, player)

print(board)


[[2 2 1]
 [0 1 0]
 [0 1 2]]


In [15]:
def row_win(board, player):
    if np.any(np.all(board==player, axis=1)): # this checks if any row contains all positions equal to player.
        return True
    else:
        return False

row_win(board, 1)

False

In [16]:
def col_win(board, player):
    if np.any(np.all(board==player, axis=0)): # this checks if any column contains all positions equal to player
        return True
    else:
        return False

col_win(board, 1)

False

In [17]:
def diag_win(board, player):
    if np.all(np.diag(board)==player) or np.all(np.diag(np.fliplr(board))==player):
        # np.diag returns the diagonal of the array
        # np.fliplr rearranges columns in reverse order
        return True
    else:
        return False

diag_win(board, 2)

False

In [18]:
def evaluate(board):
    winner = 0
    for player in [1, 2]:
        if row_win(board, player) or col_win(board, player) or diag_win(board, player):
            winner = player
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner

evaluate(board)

0

In [19]:
random.seed(1)

def play_game():
    board = create_board()
    winner = 0
    while winner == 0:
        for player in [1, 2]:
            random_place(board, player)
            winner = evaluate(board)
            if winner != 0:
                break
    return winner

results = [play_game() for i in range(1000)]
results.count(1)

591